
on: [push]

name: AzureCLISample

jobs: 

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
          
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: deploy ML workspace
      uses: azure/CLI@v1 
      with:
        azcliversion: 2.9.1
        inlineScript: |
          az deployment group create --resource-group ${{ secrets.RESOURCE_GROUP }} --template-file .cloud/.azure/deploy.json \
          --parameters .cloud/.azure/deploy.params.json patToken=${{secrets.PATTOKEN}} repo_name=$GITHUB_REPOSITORY

  
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          name: ${{secrets.WORKSPACE_NAME}}
      
    # Submit a training run to the Azure Machine Learning
    - name: Submit training run
      id: aml_run
      uses: Azure/aml-run@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
